mini_batch_size: 32
batch_num_per_epoch: 100_000
replay_buffer_size: 200_000
training_steps: 20_000_000
skip_k_frame: 4
phi_channel: 4
device: 'cuda: 0'
screen_size: 84
replay_start_size: 10_000
gamma: 0.99
no_op: 30
save_path: './data_log/'
log_path: '../exps/dqn_qq/'
learning_rate: 0.000001
step_c: 10_000
epsilon_max: 1.
epsilon_min: 0.1
exploration_steps: 1_000_000
epsilon_for_test: 0.05
agent_test_episodes: 20
agent_saving_period: 80000